objects/Account/fields/This_Month_Total_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>This_Month_Total_Payment_Amount__c</fullName>
    <label>This Month Total Payment Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Payment__c/fields/Final_Amount__c.field-meta.xml
<CustomField>
    <fullName>Final_Amount__c</fullName>
    <label>Final Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Payment__c/fields/Payment_date__c.field-meta.xml
<CustomField>
    <fullName>Payment_date__c</fullName>
    <label>Payment date</label>
    <type>Date</type>
</CustomField>

classes/CalculateThisMonthPaymentAmountBatch.cls
global  class CalculateThisMonthPaymentAmountBatch implements Database.Batchable<sObject>, Database.Stateful{

    //total Amount
    public Decimal totalAmount = 0;

    //update Accout list
    List<Account> updateAccoutList = new List<Account>();

    //Start method
    global  Database.QueryLocator start(Database.BatchableContext BC){
        String query = 'SELECT Id, This_Month_Total_Payment_Amount__c, (SELECT Id , Final_Amount__c, Payment_date__c  from Payments__r WHERE Payment_date__c = THIS_MONTH) FROM Account ';
        return Database.getQueryLocator(query);
    }
 
    //Execute method
    global  void execute(Database.BatchableContext BC, List<Account> scope){
        // process each batch of records

        for (Account acc : scope) {
            Account accObj = new Account ();
            
            for (Payment__c payment : acc.Payments__r){
                if(payment.Final_Amount__c > 0){
                    totalAmount += payment.Final_Amount__c;
                }  
            }

            accObj.Id = acc.Id;
            accObj.This_Month_Total_Payment_Amount__c = totalAmount;

            // add to update list
            updateAccoutList.add(accObj);
        }
    }
 
    //Finish method 
    global  void finish(Database.BatchableContext BC){
        if(updateAccoutList.size() > 0){
            update updateAccoutList;
        }
    }
 }