objects/Account/fields/This_Month_Total_Payment_Amount__c.field-meta.xml
<CustomField>
    <fullName>This_Month_Total_Payment_Amount__c</fullName>
    <label>This Month Total Payment Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Payment__c/Payment__c.object-meta.xml
<CustomObject>
    <label>Payment</label>
    <nameField>
        <label>Payment Name</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Payment__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Payment__c/fields/Final_Amount__c.field-meta.xml
<CustomField>
    <fullName>Final_Amount__c</fullName>
    <label>Final Amount</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

objects/Payment__c/fields/Payment_date__c.field-meta.xml
<CustomField>
    <fullName>Payment_date__c</fullName>
    <label>Payment date</label>
    <type>Date</type>
</CustomField>

classes/CalculateThisMonthPaymentAmountBatchTest.cls
@isTest
private class CalculateThisMonthPaymentAmountBatchTest {
    @testSetup
    static void setup() {
        List<Account> accounts = new List<Account>();
        List<Payment__c> payments = new List<Payment__c>();

        // insert 1 accounts
        accounts.add(new Account(Name='Account test 1234'));
    
        insert accounts;

        // find the account just inserted. add contact for each
        for (Account account : [select id from account where Name='Account test 1234']) {
            payments.add(new Payment__c(Name='payment test',
            Amount__c=1200,Final_Amount__c = 1300,Payment_date__c = date.parse('2023/03/15'), Account__c=account.id));
        }
        insert payments;
    }
    @isTest static void test() {
        Test.startTest();
        CalculateThisMonthPaymentAmountBatch uca = new CalculateThisMonthPaymentAmountBatch();
        Id batchId = Database.executeBatch(uca);
        Test.stopTest();

        List<Account> accounts = [select 	This_Month_Total_Payment_Amount__c from Account where Name='Account test 1234'];

        // after the testing stops, assert records were updated properly
        System.assertEquals(1300, accounts[0].This_Month_Total_Payment_Amount__c);
    } 
}